#docker-compose for meddream viewport demo
services:
  # Orthanc PACS Server
  orthanc:
    image: jodogne/orthanc-python
    platform: linux/amd64
    container_name: orthanc
    restart: always
    ports:
      - "4242:4242"  # DICOM protocol port
      - "8042:8042"  # HTTP API port
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./meddream.py:/etc/orthanc/meddream.py:ro
      - orthanc-db:/var/lib/orthanc/db/
    networks:
      - meddream-net
   

  # MEDDREAM DICOM Viewer
  meddream:
    image: meddream/dicom-viewer:8.6.0
    platform: linux/amd64
    container_name: meddream
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/application.properties:/opt/meddream/application.properties:ro
    networks:
      - meddream-net
    depends_on:
     - orthanc
    

  # Frontend Web Server (nginx)
  frontend:
    image: nginx:alpine
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - meddream-net
    depends_on:
      - meddream
   

  # One-time service to load sample DICOM data
  dicom-loader:
    image: meddream/dicom-studies:latest
    container_name: dicom-loader
    platform: linux/amd64
    networks:
      - meddream-net
    depends_on:
      - orthanc
    command: storescu -cSENDTOPACS@orthanc:4242 /opt/DICOM
    restart: "no"  # Only run once
    profiles:
      - tools  # Optional profile - run with: docker-compose --profile tools up

  # Build service for frontend (run when needed)
  builder:
    image: node:18-alpine
    container_name: builder
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - NPM_TOKEN=${NPM_TOKEN:-}
    command: sh -c 'npm i && npm run build'
    restart: "no"
    profiles:
      - build  # Run with: docker-compose --profile build up builder

volumes:
  orthanc-db:
    driver: local

networks:
  meddream-net:
    driver: bridge
    name: meddream-network